### ISSUE TITLE
ArgumentError (wrong number of arguments (given 2, expected 1))

### ISSUE THREAD

**Issue by sandy1987** [anycable/anycable-rails#22] opened 2017-11-21 14:53 UTC
Hello,

Please let me know the solution, So I will update the code as well
I have follow this links
https://github.com/anycable/anycable-rails

ArgumentError (wrong number of arguments (given 2, expected 1)):
  
anycable-rails (0.5.0) lib/anycable/rails/actioncable/connection.rb:29:in `initialize'
actioncable (5.0.6) lib/action_cable/server/base.rb:28:in `new'
actioncable (5.0.6) lib/action_cable/server/base.rb:28:in `call'
actionpack (5.0.6) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.0.6) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.0.6) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.6) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.6) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.6) lib/action_dispatch/routing/route_set.rb:727:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.6) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.6) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.6) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.6) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.6) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.6) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.6) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.6) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.6) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.6) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.6) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.0.6) lib/rails/engine.rb:522:in `call'
puma (3.11.0) lib/puma/configuration.rb:225:in `call'
puma (3.11.0) lib/puma/server.rb:624:in `handle_request'
puma (3.11.0) lib/puma/server.rb:438:in `process_client'
puma (3.11.0) lib/puma/server.rb:302:in `block in run'
puma (3.11.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
  Rendering /home/yuva/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /home/yuva/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /home/yuva/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (3.1ms)
  Rendering /home/yuva/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /home/yuva/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.3ms)
  Rendering /home/yuva/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /home/yuva/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.3ms)
  Rendered /home/yuva/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (23.3ms)

**Comment by dmcclory** [comment] 2017-11-21 19:59
I also hit this today! I followed the steps in the anycable-rails README and encountered a very similar similar stacktrace when I ran it on these 2 combinations of versions:

- `anycable (0.4.6), anycable-rails (0.4.7), and rails (5.1.0.rc1)`
- `anycable (0.5.0), anycable-rails (0.5.0), and rails (5.1.0.rc1)`

It might just be that the README is a little out of date? I'm going to keep poking around.

**Comment by palkan** [comment] 2017-11-22 06:37
The problem is that you're trying to connect to Action Cable server and not to AnyCable (this line form backtrace `lib/action_cable/server/base.rb:28:in new'`).

You should set up `config.action_cable.url = "<URL for anycable-go application>"` in your `application.rb` to make sure that JS client connects to the correct server.

Looks like your Action Cable server is mounted to your Rack stack. Do you have `config.action_cable.mount_path = '/whatever'` set in your configuration?

Also, how do you require `anycable-rails` (or how your Gemfile looks like)?

**Comment by sandy1987** [comment] 2017-11-22 08:47
Hello @palkan ,

Please let me know one things can we run application on different heroku server and we will use this url of that server

 config.action_cable.url = "<URL for anycable-go application>"
"<URL for anycable-go application>" In place of this

**Comment by palkan** [comment] 2017-11-22 11:00
> can we run application on different heroku server and we will use this url of that server

If I understand your question correctly (I'm not sure), then – yes, you should use the url of the second server (running RPC and anycable-go) as `action_cable.url`.

**Comment by Crashtor** [comment] 2017-11-23 11:06
@palkan I get this error message as well. Your solution won't work for me, still getting the exact same error as @sandy1987.

**Comment by palkan** [comment] 2017-11-23 12:49
There is definitely something with configuration but it's not easy to figure our what exactly without having an access to the codebase. So, if it's possible, please, share your code with me. Otherwise let's try other ways.

For example, it could be useful to _see_ what's going on. Could you record a video demonstrating the problem? With server and browser network logs.

Logs also could be useful: turn on debug mode (in Rails `config.log_level = :debug`, for anycable-go – `anycable-go -log`). And send these logs to me.

**Comment by CR4567** [comment] 2017-11-23 16:32
Hey guys,
I was also working on the same problem for the last days. And like @palkan already mentioned, it was a problem of the configuration. The clients were always trying to connect to the "old" actioncable and to localhost instead of the correct path. So when I changed to
`  App.cable = ActionCable.createConsumer("ws://URL:PORT");
`
clients connected to the correct server and using 
`sudo ./anycable-go-0.5.1-linux-amd64 -addr='URL:PORT'`
for the server, problem was solved.

Maybe this helps you too.

**Comment by CR4567** [comment] 2017-11-24 10:32
hm... it seems that I was wrong... the error still occurs and I get a handshake error even with setting 
`config.action_cable.allowed_request_origins = [/http:\/\/*/, /https:\/\/*/]`
what seems to be the typical reason.
I will try to investigate further but also open for new ideas :-D

**Comment by palkan** [comment] 2017-11-24 10:41
@CR4567 Hm, when using AnyCable `allowed_request_origins` is not used. 

> `App.cable = ActionCable.createConsumer("ws://URL:PORT");`

The path is missing as I see, should be: `"ws://URL:PORT/cable"`

**Comment by CR4567** [comment] 2017-11-24 10:50
@palkan ah thanks for the info... 
so i can comment all the lines about the request origins...
but I already added the missing /cable to the path without any change....
my browser inspector gives me following error:
`VM1864:164 WebSocket connection to 'ws://testing.easierlife.de:3334/' failed: Error during WebSocket handshake: Unexpected response code: 404`
and stacktrace:
`WrappedWebSocket @ VM1864:164
ActionCable.Connection.Connection.open @ intern-6b02134866f9eaf3198fff1bd45d69cd7c737c1a7e5f25b9bf0fd48e2b8f726d.js:28747
(anonymous) @ intern-6b02134866f9eaf3198fff1bd45d69cd7c737c1a7e5f25b9bf0fd48e2b8f726d.js:28711
ActionCable.Consumer.Consumer.ensureActiveConnection @ intern-6b02134866f9eaf3198fff1bd45d69cd7c737c1a7e5f25b9bf0fd48e2b8f726d.js:29091
ActionCable.Subscriptions.Subscriptions.add @ intern-6b02134866f9eaf3198fff1bd45d69cd7c737c1a7e5f25b9bf0fd48e2b8f726d.js:28908
ActionCable.Subscriptions.Subscriptions.create @ intern-6b02134866f9eaf3198fff1bd45d69cd7c737c1a7e5f25b9bf0fd48e2b8f726d.js:28903
App.Channels.InternEvent.subscribe @ intern-6b02134866f9eaf3198fff1bd45d69cd7c737c1a7e5f25b9bf0fd48e2b8f726d.js:29192
(anonymous) @ intern-6b02134866f9eaf3198fff1bd45d69cd7c737c1a7e5f25b9bf0fd48e2b8f726d.js:29637
`
I'm sure it's just a config problem but right now it feels like I tried most of the options :-(
Could it be a problem with nginx? 
I'm just wondering because it worked before with actioncable

**Comment by palkan** [comment] 2017-11-24 11:04
> WebSocket connection to 'ws://testing.easierlife.de:3334/' failed:

Hm, there should be `ws://testing.easierlife.de:3334/cable` then.
Try to run the following in your browser console:

```js
new WebSocket('ws://testing.easierlife.de:3334/cable')
```

**Comment by CR4567** [comment] 2017-11-24 11:07
oh boy... that was kind of stupid... 
yeah I was also wondering why it still connects to the wrong url.
So the main problem was that I forgot to precompile the assets and still was on the old version... the reason why the url didn't changed... after precompiling now finally everything is running perfectly fine.... thanks a lot for you patience :-D

**Comment by Crashtor** [comment] 2017-11-25 00:34
I redid the whole heroku tutorial to the teeth, and while it seem to be connecting, I get a weird error when I try to send a chat message,

`[NoMethodError - undefined method `[]' for false:FalseClass]:`

`/app/vendor/bundle/ruby/2.3.0/gems/anyway_config-0.4.0/lib/anyway/rails/config.rb:13:in `load_from_file' | /app/vendor/bundle/ruby/2.3.0/gems/anyway_config-0.4.0/lib/anyway/rails/config.rb:4:in `load_from_sources' | /app/vendor/bundle/ruby/2.3.0/gems/anyway_config-0.4.0/lib/anyway/config.rb:52:in `load' | /app/vendor/bundle/ruby/2.3.0/gems/anyway_config-0.4.0/lib/anyway/config.rb:35:in `initialize' | /app/vendor/bundle/ruby/2.3.0/gems/anycable-0.3.0/lib/anycable.rb:23:in `new'`

What could be causing this?

**Comment by palkan** [comment] 2017-11-26 13:52
@Crashtor Can you show me the logs for RPC app? Usually, 502 means that something went wrong with proxy (Heroku router?). There should be errors in the log.

> mount ActionCable.server => '/cable'

You don't need this in your `routes.rb` (that explains the initial problem – connecting to the Rails Action Cable server). 
Rails automatically mounts Action Cable if `config.action_cable.mount_path` is not `nil`.

**Comment by Crashtor** [comment] 2017-11-26 13:55
2017-11-25T23:06:14.067927+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/cable" host=trotter-rpc.herokuapp.com request_id=c54cf39f-337a-4a5e-9be9-c4e438a75c9d fwd="80.216.213.189" dyno= connect= service= status=502 bytes= protocol=https
2017-11-25T23:06:21.578307+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/cable" host=trotter-rpc.herokuapp.com request_id=f86df7f8-eec1-4ce8-a17d-d603d74b04f1 fwd="80.216.213.189" dyno= connect= service= status=502 bytes= protocol=https
2017-11-25T23:06:31.606320+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/cable" host=trotter-rpc.herokuapp.com request_id=0ae91cac-9c21-46c7-b821-3ee78f7e62a3 fwd="80.216.213.189" dyno= connect= service= status=502 bytes= protocol=https
2017-11-25T23:06:43.219509+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/cable" host=trotter-rpc.herokuapp.com request_id=8d5b13f1-5937-4ca2-82c8-0ef3fdf68061 fwd="80.216.213.189" dyno= connect= service= status=502 bytes= protocol=https
2017-11-25T23:06:50.995838+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/cable" host=trotter-rpc.herokuapp.com request_id=72924211-c37c-4c9d-866f-d4dcf6eeff04 fwd="80.216.213.189" dyno= connect= service= status=502 bytes= protocol=https
2017-11-25T23:07:01.590399+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/cable" host=trotter-rpc.herokuapp.com request_id=04316066-ce13-4520-97cd-e5da133eb3f8 fwd="80.216.213.189" dyno= connect= service= status=502 bytes= protocol=https
2017-11-25T23:07:14.487926+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/cable" host=trotter-rpc.herokuapp.com request_id=d9fdeef6-96b1-4292-b297-143c629b9887 fwd="80.216.213.189" dyno= connect= service= status=502 bytes= protocol=https
2017-11-25T23:07:27.880480+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/cable" host=trotter-rpc.herokuapp.com request_id=cecbae8f-2b9c-40b7-9d5d-c9f6b63b6497 fwd="80.216.213.189" dyno= connect= service= status=502 bytes= protocol=https
2017-11-25T23:07:40.530991+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/cable" host=trotter-rpc.herokuapp.com request_id=a561fcee-9d86-4798-9a3b-ee882d2e3d59 fwd="80.216.213.189" dyno= connect= service= status=502 bytes= protocol=https
2017-11-25T23:07:53.982357+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/cable" host=trotter-rpc.herokuapp.com request_id=79cc2652-9ba4-4a75-bdfd-95159b28df6a fwd="80.216.213.189" dyno= connect= service= status=502 bytes= protocol=https
2017-11-25T23:08:10.092004+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/cable" host=trotter-rpc.herokuapp.com request_id=d2dd74b2-e255-4227-b6e4-8e4dc2cf6bb9 fwd="80.216.213.189" dyno= connect= service= status=502 bytes= protocol=https

**Comment by palkan** [comment] 2017-11-26 14:19
@Crashtor Hm, Heroku says that there is no applicant code (https://devcenter.heroku.com/articles/error-codes#h81-blank-app).

Maybe, you forgot to push your repo to the second, RPC, remote?

I've just noticed that this step is missing in the wiki. My bad( Updated.

**Comment by Crashtor** [comment] 2017-11-26 15:02
Ok yes, that was correct, I had not done that. Now I have however, and here are the logs from the rpc app:

2017-11-26T15:01:36.104484+00:00 heroku[web.1]: Starting process with command `ANYCABLE_REDIS_URL=redis://h:pb85411ac3120d265445ff790c6dc45bb651ae77187cee54480afcee39a7905bd@ec2-34-252-202-201.eu-west-1.compute.amazonaws.com:27939 REDIS=redis://h:pb85411ac3120d265445ff790c6dc45bb651ae77187cee54480afcee39a7905bd@ec2-34-252-202-201.eu-west-1.compute.amazonaws.com:27939 ADDR="0.0.0.0:12110" CABLE_URL='wss://app-rpc.herokuapp.com/cable' bin/heroku-web`
2017-11-26T15:01:44.094050+00:00 app[web.1]: /app/app/models/concerns/stripe_tool.rb:2: warning: circular argument reference - email
2017-11-26T15:01:44.094072+00:00 app[web.1]: /app/app/models/concerns/stripe_tool.rb:2: warning: circular argument reference - stripe_token
2017-11-26T15:01:44.094073+00:00 app[web.1]: /app/app/models/concerns/stripe_tool.rb:9: warning: circular argument reference - customer_id
2017-11-26T15:01:44.094074+00:00 app[web.1]: /app/app/models/concerns/stripe_tool.rb:9: warning: circular argument reference - amount
2017-11-26T15:01:44.094074+00:00 app[web.1]: /app/app/models/concerns/stripe_tool.rb:9: warning: circular argument reference - description
2017-11-26T15:01:44.094077+00:00 app[web.1]: /app/app/models/concerns/stripe_tool.rb:9: warning: circular argument reference - last4
2017-11-26T15:01:44.244602+00:00 app[web.1]: bundler: failed to load command: ./bin/anycable (./bin/anycable)
2017-11-26T15:01:44.247816+00:00 app[web.1]: NoMethodError: undefined method `[]' for nil:NilClass
2017-11-26T15:01:44.247819+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/anyway_config-1.1.2/lib/anyway/rails/config.rb:22:in `load_from_file'
2017-11-26T15:01:44.247820+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/anyway_config-1.1.2/lib/anyway/rails/config.rb:14:in `load_from_sources'
2017-11-26T15:01:44.247820+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/anyway_config-1.1.2/lib/anyway/config.rb:73:in `load'
2017-11-26T15:01:44.247821+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/anyway_config-1.1.2/lib/anyway/config.rb:56:in `initialize'
2017-11-26T15:01:44.247822+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/anycable-0.5.0/lib/anycable/config.rb:20:in `initialize'
2017-11-26T15:01:44.247822+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/anycable-0.5.0/lib/anycable.rb:34:in `new'
2017-11-26T15:01:44.247823+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/anycable-0.5.0/lib/anycable.rb:34:in `config'
2017-11-26T15:01:44.247824+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/anycable-0.5.0/lib/anycable/server.rb:13:in `start'
2017-11-26T15:01:44.248915+00:00 app[web.1]:   /app/bin/anycable:19:in `<top (required)>'
2017-11-26T15:01:44.274656+00:00 app[web.1]: Running AnyCable websocket server v0.4.1 on 0.0.0.0:12110 at /cable
2017-11-26T15:01:44.547586+00:00 heroku[web.1]: Process exited with status 1
2017-11-26T15:01:44.561620+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by palkan** [comment] 2017-11-26 15:15
@Crashtor Looks like your `config/anycable.yml` exists but empty, because `YAML.safe_load` returns `nil`. Is this a case?

**Comment by Crashtor** [comment] 2017-11-26 15:16
Ops, yes. Correct.

**Comment by Crashtor** [comment] 2017-11-26 15:24
Yessss. Here we go! Now, using Devise, I ran into the auth_failed as described in the Heroku tutorial.
Go ahead and close this up Vladimir. Thank you so much for your help!

**Comment by palkan** [comment] 2017-11-26 15:25
🎉 🎉 🎉 
We did it)

**Closed by palkan** 2017-11-26 15:25 UTC

**Comment by birthdaycorp** [comment] 2019-12-23 08:22
hi @palkan! i just had this issue, and was wondering if you could clarify something about your answers?

[this](https://docs.anycable.io/#/ruby/rails) link says to use `config.action_cable.url = 'ws://localhost:3334/cable'` in development config. i have that set, but my routes.rb file has `mount ActionCable.server => '/cable'`. does this mean i'm still using ActionCable? should i remove that from routes? i get the same line in the stacktrace - `actioncable (5.2.0) lib/action_cable/server/base.rb:30:in `new'`

**Comment by sponomarev** [comment] 2019-12-23 10:31
@birthdaycorp If it reaches Rails's router, it means that `config.action_cable.url` is not properly set for the corresponding environment. When AnyCable is used, your frontend should reach websocket backend directly.

Just to make sure, that this option is set and passed properly, check `action-cable-url` meta tag on a page.

<img width="652" alt="image" src="https://user-images.githubusercontent.com/2322774/71352840-6b0cc380-2588-11ea-8471-dfee991fde41.png">

**Comment by birthdaycorp** [comment] 2019-12-23 23:30
thanks @sponomarev ! the meta tag in my dev environment says `<meta name="action-cable-url" content="ws://localhost:3000/cable">`. It was previously on port 3334, but I changed it to 3000 in search of possible reasons as to why it was not working. Neither worked

**Comment by sponomarev** [comment] 2019-12-24 13:00
@birthdaycorp If you want to use AnyCable in all environments including development, make sure that you set `config.action_cable.url ` andws server is running. Nothing related to ActionCable in routes is necessary.

Can you describe what happens when you do all of that?

**Comment by birthdaycorp** [comment] 2019-12-24 19:35
@sponomarev my config is set as `config.action_cable.url = 'ws://localhost:3334/cable'` and i'm running `bundle exec anycable --server-command "anycable-go --host=localhost --port=3334"`

I'll send a message to one user, the message will persist to the db,  followed by an ActionCable broadcast `[ActionCable] Broadcasting to messages:...`, and then it hits this:

    Started GET "/cable" for ::1 at 2019-12-24 11:31:46 -0800
  
    ActionController::RoutingError (No route matches [GET] "/cable"):

**Comment by palkan** [comment] 2019-12-25 15:52
@birthdaycorp What shows the meta tag when you set `config.action_cable.url = 'ws://localhost:3334/cable'`? Does it still point to `"ws://localhost:3000/cable"`?

Where do you set `config.action_cable.url`: `config/application.rb` or `config/environments/development.rb`?

**Comment by birthdaycorp** [comment] 2019-12-25 18:25
The meta tag says `<meta name="action-cable-url" content="ws://localhost:3334/cable">`. I changed it back to 3334 since 3000 was in use by my rails server.

I have the `action_cable.url` set in `config/environments/development.rb`

**Comment by sponomarev** [comment] 2019-12-25 19:05
@birthdaycorp Are you sure that the meta tag is shown on the page which invokes WS connect and? Check all layouts for `action_cable_meta_tag`.

**Comment by birthdaycorp** [comment] 2019-12-25 19:44
I have `action_cable_meta_tag` in my `application.html.rb` file, so every page on my site has `<meta name="action-cable-url" content="ws://localhost:3334/cable">` in the header.

**Comment by birthdaycorp** [comment] 2019-12-31 01:50
Update: I _think_ I'm on the right path. I've managed to turn the previous error (`ActionController::RoutingError (No route matches [GET] "/cable"):`) into `WebSocket connection to 'ws://localhost:3334/cable' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`. 

Currently getting to the bottom of that, but turns out there a number of things that it would be helpful to specify in the docs.


1. Your `cable.coffee` or whatever file should have the WebSockets url in the argument to `createConsumer`. In my case, this looks like: `App.cable = ActionCable.createConsumer("ws://localhost:3334/cable")`
2. run `rake assets:precompile` (what @CR4567 said above)
3. `<%= action_cable_meta_tag %>` should load BEFORE your `javascript_include_tag`. I figured that out by seeing an example [here](https://www.driftingruby.com/episodes/actioncable-part-1-configuration-and-basics)

**Comment by palkan** [comment] 2019-12-31 13:59
> getting to the bottom of that, but turns out I just needed t make sure that my action_cable_meta_tag was loaded BEFORE my javascript_include_tag

Good catch!

I'd suggest to create consumer on DOM load event instead, no reason to initiate the connection 
before the page is ready.

> WebSocket connection to 'ws://localhost:3334/cable' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED.

Try to run `anycable-go` with `-debug` flag and check logs. Probably, authentication problem or RPC server is not running (`bundle exec anycable`).

**Comment by birthdaycorp** [comment] 2020-01-02 05:17
Thanks for that DOM load suggestion, it was helpful. 

This is so weird, though. I'll changing nothing, and it only works half the time.

I'll run `rails s` and `redis-server`and then `bundle exec anycable --server-command "anycable-go --host=localhost --port=3334"`, and AnyCable will "work" in the sense that the anycable terminal starts spitting out this:

    [[AnyCable sid=6y3lH9onvpRGHeZTicREiG] undefined method `user' for nil:NilClass
    [AnyCable sid=4bu5UsMf2w0zg8hYZ4VawU] RPC Connect: <AnyCable::ConnectionRequest: path: "/cable", headers: {"REMOTE_ADDR"=>"127.0.0.1", "cookie"=>"wcsid=tZAOL9lfLfqPfKTl3m39N0XFbD9b533C; hblid=wT8x32xbCiqFTWzh3m39N0XabCoa35FA; _okdetect=%7B%22token%22%3A%2215752427728670%22%2C%22proto%22%3A%22http%3A%22%2C%22host%22%3A%22localhost%3A4040%22%7D; olfsk=olfsk3463007807472125; _okbk=cd4%3Dtrue%2Cvi5%3D0%2Cvi4%3D1575242773028%2Cvi3%3Dactive%2Cvi2%3Dfalse%2Cvi1%3Dfalse%2Ccd8%3Dchat%2Ccd6%3D0%2Ccd5%3Daway%2Ccd3%3Dfalse%2Ccd2%3D0%2Ccd1%3D0%2C; _ok=1700-237-10-3483; _oklv=1575242826551%2CtZAOL9lfLfqPfKTl3m39N0XFbD9b533C; _project_session=a9932b54c129449974d491e9216c27ed; username=napoleon.waelchi; _any_cable_session=SU1nei93RnRIQnpPbUpHMzR4TlJ3ZHk3NXJKTHUzZUZHV2ZEdW1xSGRENm1XZTBkRlZpaU9PSEtSNzVXUzRMVjJDWGNCcmhtcE1mbjZoSFJUYlZ2VzJRa0JoeVFZejZKazdVVkRtU2RiZ3NpdThUZjF6UXpvU28vUkhOQktHU2JkSG12Q0RNRkNSU2hKdU1Ocm9zWGNqREExVk5IYWpwbDV4eGZnSm1XUUxNUmoyZ2JqWCtvelZnUHhjVFR5cU5VLS1ZemRPb1haWENkYjVCQk1Xc1NyQWxnPT0%3D--abe49698b042ab3803511681be634df58f228a9b"}>](url)

I was initially going to ask where that `username=napoleon.waelchi` was coming from (I remember seeing that username in the demo, but I'm not running the demo), but then AnyCable magically went back to not working. Now it's back to this in my rails terminal:

    Started GET "/cable" for ::1 at 2020-01-01 21:06:24 -0800
    ActionController::RoutingError (No route matches [GET] "/cable"):
    actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'

**Comment by palkan** [comment] 2020-01-02 14:32
@birthdaycorp 

> undefined method `user' for nil:NilClass

What's in your `ApplicationCable::Connection#connect`?

> Where is that username=napoleon.waelchi coming from?

It's a part of the cookies.

**Comment by birthdaycorp** [comment] 2020-01-04 19:27
Thank you so much for your continued help with this! If I open Chrome inspector, I see that the cookie variables are all exactly the same as the output from `bundle exec anycable`. But that username does not belong to any user model I'm working with.

I followed the Devise integration [here](https://docs.anycable.io/#/ruby/authentication?id=devisewarden), and managed to fix that `undefined method 'user'` error with a new error: `[AnyCable sid=qhREBuLEC3RfUFyzzAngul] An unauthorized connection attempt was rejected`.  it would seem that I'm making one successful `anycable-go` connection, but rejecting the rest? 

I guess a better way to phrase my question is: why is the one working `anycable-go` connection on a user model with a username that I don't have in my database?

**Comment by palkan** [comment] 2020-01-05 00:27
> But that username does not belong to any user model I'm working with.

Do you set `cookies[:username]` somewhere in your code? Or have your tried to run `anycable_demo` app (we have such cookies usage there)? Probably, just a cookie left from something else. Have you tried to clear the browser cookies?

**Comment by birthdaycorp** [comment] 2020-01-13 00:50
I'm still trying to figure out how to make this work, but would you have any idea why the anycable console keeps spitting out `[AnyCable sid=ZyR-1n5t1oapkFM29g8fL0] An unauthorized connection attempt was rejected` before and/or after every successful connection?
