### ISSUE TITLE
Rack Error

### ISSUE THREAD

**Issue by rus-max** [anycable/anycable-rails#119] opened 2020-03-18 08:35 UTC
Hello!

**Ruby version:"" 2.6.5

**Rails version:** 5.2.4.1

**`anycable` gem version:** 1.0preview1

**`anycable-rails` gem version:** 1.0preview1

**`grpc` gem version:** 1.27.0

### What did you do?

Upgrade AnyCable to 1.0preview1

### What did you expect to happen?

```
INFO -- : Starting AnyCable gRPC server (pid: 30603, workers_num: 30)
INFO -- : AnyCable version: 1.0.0.preview1 (proto_version: v1)
INFO -- : gRPC version: 1.27.0
INFO -- : Serving Rails application from ./config/anycable.rb
INFO -- : handling /anycable.RPC/Connect with #<Method: AnyCable::RPCHandler#connect>
INFO -- : handling /anycable.RPC/Command with #<Method: AnyCable::RPCHandler#command>
INFO -- : handling /anycable.RPC/Disconnect with #<Method: AnyCable::RPCHandler#disconnect>
INFO -- : handling /grpc.health.v1.Health/Check with #<Method: Grpc::Health::Checker#check>
INFO -- : handling /grpc.health.v1.Health/Watch with #<Method: Grpc::Health::Checker(Grpc::Health::V1::Health::Service)#watch>
INFO -- : Broadcasting Redis channel: __anycable__
INFO -- : RPC server is starting...
INFO -- : RPC server is listening on localhost:50051
INFO -- : Started command: ./bin/anycable-go-v1.0.0p --port=3334 --path=/ws --rpc_host=localhost:50051 --metrics_log (pid: 32487)
INFO -- : deadline is 1970-01-01 02:59:59 +0300; (now=2020-03-18 11:29:19 +0300)
INFO -- : schedule another job
ERROR -- : [AnyCable sid=2aec5c23593a4d21554f545a79140f63] invalid value for Integer(): "":
gems/rack-2.2.2/lib/rack/request.rb:252:in `Integer'
gems/rack-2.2.2/lib/rack/request.rb:252:in `server_port'
gems/rack-2.2.2/lib/rack/request.rb:235:in `server_authority'
gems/rack-2.2.2/lib/rack/request.rb:228:in `authority'
gems/rack-2.2.2/lib/rack/request.rb:297:in `host'
gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/transaction/request_attributes.rb:110:in `attribute_from_request'
gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/transaction/request_attributes.rb:22:in `initialize'
gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/transaction.rb:261:in `new'
gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/transaction.rb:261:in `initialize'
gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/transaction.rb:130:in `new'
gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/transaction.rb:130:in `start_new_transaction'
gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/tracer.rb:155:in `start_transaction_or_segment'
gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:91:in `call'
gems/anycable-rails-1.0.0.preview1/lib/anycable/rails/actioncable/connection.rb:198:in `build_rack_request'
gems/anycable-rails-1.0.0.preview1/lib/anycable/rails/actioncable/connection.rb:140:in `request'
gems/anycable-rails-1.0.0.preview1/lib/anycable/rails/actioncable/connection.rb:150:in `started_request_message'
gems/anycable-rails-1.0.0.preview1/lib/anycable/rails/actioncable/connection.rb:55:in `handle_open'
gems/anycable-1.0.0.preview1/lib/anycable/rpc_handler.rb:20:in `connect'
gems/grpc-1.27.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `call'
gems/grpc-1.27.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `block in handle_request_response'
```

**Comment by palkan** [comment] 2020-03-18 14:25
Thanks for the report!

I was able to reproduce it only with Rack 2.2.2 (works with Rack 2.0.x). Will take a closer look (and hopefully fix) soon.

**Comment by palkan** [comment] 2020-03-18 16:22
@rus-max It should be fixed now. You can try the fix by using the `anycable` gem from GitHub:

```ruby
gem "anycable", github: "anycable/anycable", branch: "1.0-dev"
```

Feel free to re-open the issue if problem won't go away.

Btw, have you added NewRelic instrumentation manually to the AnyCable Rack middleware? Or it somehow got auto-injected? I don't think we need for AnyCable, since we use middleware only to populate Rack env.

**Comment by rus-max** [comment] 2020-03-18 16:22
Thanks for the great work!

**Closed by palkan** 2020-03-18 16:22 UTC
Labels: bug

**Comment by rus-max** [comment] 2020-03-18 16:30
NewRelic auto-injected in monitor mode
